### ISSUE TITLE
No CDS (proteins) detected in reference

### ISSUE THREAD

**Issue by jojobmz** [alexchwong/SpliceWiz#13]
Hello, teacher, 
I've been learning the software splicewiz recently to recognize alternative splicing. But I encountered some difficulties. When I create a reference, I always prompt that CDs is not detected. I used Chr_ Z genome and GTF in the manual respectively, as well as my own sequence files, will appear in this situation. What is the reason? Also, when I enter the path, other errors will be prompted. 
Please see the picture for details. 
I hope the teacher can reply to me, thank you！
![1](https://user-images.githubusercontent.com/81802864/181148202-71af865e-8db0-49ad-bba4-7609780aa155.png)
![2](https://user-images.githubusercontent.com/81802864/181148204-5de1377f-d38a-4df2-b6e7-d4aaad3626d3.png)
![3](https://user-images.githubusercontent.com/81802864/181148206-1f2d67c8-1d64-488c-838e-8556eb1bb49c.png)

**Comment by alexchwong** [comment]
Hi there,

What source GTF file are you using? It looks like the GTF does not contain any entries that correspond to type = "CDS" which annotates protein coding sequences. These are often differences from exons (type = "exon"), as proteins are translated between start and stop codons.

Could you use a FASTA and GTF file from Ensembl for your species of interest?

**Comment by jojobmz** [comment]
> Hi there,
> 
> What source GTF file are you using? It looks like the GTF does not contain any entries that correspond to type = "CDS" which annotates protein coding sequences. These are often differences from exons (type = "exon"), as proteins are translated between start and stop codons.
> 
> Could you use a FASTA and GTF file from Ensembl for your species of interest?

I use extdata of the software package "Nxtirfdata". I browsed its GTF file, which contains the complete "CDs".

But I also used my own file, which was downloaded from NCBI. However, the GTF of NCBI divides CDs into different fragments.

I need about thirty species, and Ensembl doesn't contain all of them.

I have a problem. Does "buildref" need to input what I study or something else? Since I first came into contact with R, I asked a lot of childish questions. I hope the teacher will understand and I will study hard.Thanks！

**Comment by alexchwong** [comment]
If you could provide me an online link to the gtf file which is causing this issue I could investigate it further.

**Comment by jojobmz** [comment]
> If you could provide me an online link to the gtf file which is causing this issue I could investigate it further.

Thank you for helping me check the errors! ^_^
this is "Apostasia shenzhenica", one of the species of Orchidaceae.
ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/plant/Apostasia_shenzhenica/latest_assembly_versions/GCA_002786265.1_ASM278626v1/[GCA_002786265.1_ASM278626v1_genomic.fna.gz

[GCA_002786265.1_ASM278626v1_genomic.gtf.gz](ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/plant/Apostasia_shenzhenica/latest_assembly_versions/GCA_002786265.1_ASM278626v1/GCA_002786265.1_ASM278626v1_genomic.gtf.gz)

**Comment by alexchwong** [comment]
It seems that the NCBI's GTF files have transcript_biotype = "mRNA". Previously SpliceWiz only assesses introns of transcripts labelled as "protein_coding", "processed_transcript", "lincRNA", "antisense", or "nonsense_mediated_decay". I've made some changes to the code to accept "mRNA". Make sure you set useExtendedTranscripts = TRUE in buildRef().

I've also fixed the code that allows for compatibility with GTF files that do not contain any CDS / start / stop codon entries. I mainly work with human and mouse so I am not able to test the code on unusual species. Let me know if you run into any further problems.

It seems there are no annotated alternative splicing events for Apostasia_shenzhenica, so you will only be able to test for intron retention events.

**Comment by alexchwong** [comment]
To use the updated code, you will have to reinstall SpliceWiz using devtools::install_github() as per the readme.

**Comment by jojobmz** [comment]
Thank you for helping me! I replied to you many times a few days ago, but I haven't been able to reply to you in time due to poor network or "no reply time". so sorry!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alexchwong/SpliceWiz"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月4日(星期四) 上午7:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alexchwong/SpliceWiz] No CDS (proteins) detected in reference (Issue #13)





 
Closed #13 as completed.
