### ISSUE TITLE
collateData function error -> Incompatible join types

### ISSUE THREAD

**Issue by ZLS01** [alexchwong/SpliceWiz#19]
Hello,

I am relatively new to bioinformatics, so please forgive me if this is a silly question. I am interested in generating visualizations for differential alternative splicing. I was successful in every step until I got to the "collateData" function, where it produces an error in bmerge indicating "Incompatible join types". Below is my input and output+error:

Code:

expr <- findSpliceWizOutput(pb_path)
nxtse_path <- file.path(getwd(), "NxtSE_output")
collateData(
  Experiment = expr,
  reference_path = ref_path_hg38,
  output_path = nxtse_path
)

Output:

Nov 02 12:40:49 Using MulticoreParam 1 threads
Nov 02 12:40:49 Validating Experiment; checking COV files...
Nov 02 12:40:50 Compiling Sample Stats
Nov 02 12:40:50 Compiling Junction List...merging...done
Nov 02 12:41:03 Compiling Junction Stats...merging...done
Nov 02 12:41:09 Compiling Intron Retention List...done
Nov 02 12:41:14 Tidying up splice junctions and intron retentions...
...annotating splice junctions
...grouping splice junctions
...grouping introns
...loading splice events
...compiling rowEvents
done

Nov 02 12:41:23 Generating NxtSE assays
Nov 02 12:41:23 Using MulticoreParam 1 threads
  |==============                                                                                                                              |  10%
Error: BiocParallel errors
  1 remote errors, element index: 1
  9 unevaluated and other errors
  first remote error:
Error in bmerge(i, x, leftcols, rightcols, roll, rollends, nomatch, mult, : Incompatible join types: x.seqnames (character) and i.seqnames (double)

Please let me know if you have any insight into this character/double value incompatibility, or if you need more detail of my upstream code. I am very interested in what SpliceWiz has to offer, so I hope to be able to over come this issue. 

Thanks,
Zac

**Comment by alexchwong** [comment]
Hi Zac,

Thanks for the bug report. I've not encountered this before. I am guessing that certain samples contain reads from only "numeric" chromosomes but the whole experiment contain samples with "character" chromosomes (e.g. "X", "Y", "MT").

Nevertheless, I have modified collateData() to coerce all seqnames to character before combining, so hopefully the latest commit will fix the problem. Please install from the main branch via devtools::install_github(). Let me know if you encounter any further issues.

**Comment by ZLS01** [comment]
This worked, thank you!

I have another question I was hoping you could answer: is there an option in the ASE-methods (i.e. ASE_limma or ASE_DESeq) where I can explore multiple conditions for differential AS? As far as I can decipher, it seems like the function only works for ASE analysis between two conditions (e.g. test_nom = "B", test_denom = "A") and not multi-group comparisons?

For context, I had prepared/assigned annotations to samples with: colData(se)$condition <- rep(c("A", "B", "C", "D"), each = 4)

If there is a way to analyze multi-group data within SpliceWiz, or if I am misinterpreting something, please let me know :) 

Thanks again!

Best,
Zac

**Comment by alexchwong** [comment]
Hi Zac,

For now, only comparisons between two groups is supported. In the future I may modify the ASE-methods to allow users more manual control over design matrices and testing, akin to that of DESeq2/limma.

What multi-group comparison statistics are you after? Overall p-values for whether an ASE is differentially expressed between any groups (like ANOVA)?

Alex
