### ISSUE TITLE
SpliceWiz intalltion error

### ISSUE THREAD

**Issue by rezarahman12** [alexchwong/SpliceWiz#24]
Dear SpliceWiz team
Thank you for developing this nice tool.

I'm trying to install SpliceWiz from Bioconductor with the below command:
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

# The following initializes usage of Bioc devel
BiocManager::install(version='devel')

BiocManager::install("SpliceWiz")

I'm getting the below error:
Error: Bioconductor version '3.17' requires R version '4.3'; use
  `BiocManager::install(version = '3.16')` with R version 4.2; see
  https://bioconductor.org/install

Could you please help me install SpliceWiz?

Kind regards
Reza

**Comment by alexchwong** [comment]
Hi Reza,

SpliceWiz can be installed with current release Bioconductor (3.16).

For devel version you will need to upgrade to R 4.3 (R devel).

We recommend SpliceWiz on Bioc 3.16 (current release) as it is probably more stable.

For more details: https://bioconductor.org/packages/release/bioc/html/SpliceWiz.html

**Comment by rezarahman12** [comment]
Dear Alex
Thank you for your prompt reply. 
I'm trying to install bioconductor 3.16 version, but obtained the below error (screen shot).
Could you please advise me possible solution of this error?
![image](https://user-images.githubusercontent.com/110575883/208270959-067efd71-398e-4779-8e8f-3450bf94130f.png)

Best regards
Reza

**Comment by alexchwong** [comment]
These are R core packages and are often not updateable because they are in use. Try restarting R session and retrying?

In any case you could simply try BiocManager::install("SpliceWiz") it might already be ok.

**Comment by alexchwong** [comment]
It could also be same issue as this: https://stackoverflow.com/questions/28546382/installed-directory-not-writable-cannot-update-packages-boot-class-kerns

**Comment by rezarahman12** [comment]
Dear Alex
Thank you so much. Your suggested way "BiocManager::install("SpliceWiz")" worked for me.
Thank you for your great help and time. Really appreciate it.
Best wishes
Reza
