### ISSUE TITLE
reference build step in splicewiz

### ISSUE THREAD

**Issue by rezarahman12** [alexchwong/SpliceWiz#27]
Hi Alex,

I've got a query regarding the use of an appropriate human genome fasta file. Should I use [**Homo_sapiens.GRCh38.dna.alt.fa.gz**] (https://ftp.ensembl.org/pub/release-108/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.alt.fa.gz)? 

Or do I need to use
[**Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz**] (https://ftp.ensembl.org/pub/release-108/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz) ?

I'm using the gtf file [**Homo_sapiens.GRCh38.108.gtf.gz**] (https://ftp.ensembl.org/pub/release-108/gtf/homo_sapiens/Homo_sapiens.GRCh38.108.gtf.gz).

I would highly appreciate your time and comment.
Best regards
Reza

**Comment by alexchwong** [comment]
Hi Reza,

The genome used should be the same as that used to align the BAM files. Usually, this is the primary assembly.

Alternates and haplotypes generally feature alternate alleles (e.g. SNPs, etc). These are more for mutation analysis rather than transcriptome analysis.

Alex

**Comment by rezarahman12** [comment]
Thanks a lot Alex.
