### ISSUE TITLE
Converting FASTA to local TwoBitFile...Error

### ISSUE THREAD

**Issue by rezarahman12** [alexchwong/SpliceWiz#28]
Dear Alex,

I'm getting an error message while running SpliceWiz, step Building SpliceWiz reference. 
code:
library(NxtIRFdata)
library(SpliceWiz)
#Building the SpliceWiz reference

gtf <- "gtf_fasta/Homo_sapiens.GRCh38.108.gtf"
genome <- "gtf_fasta/Homo_sapiens.GRCh38.dna.alt.fa"

ref_path <-"ref_hg38"

buildRef(
  reference_path = ref_path,
  fasta = genome,
  gtf = gtf
)

********* the error message in highlighted below:********
gtf <- "gtf_fasta/Homo_sapiens.GRCh38.108.gtf"
> genome <- "gtf_fasta/Homo_sapiens.GRCh38.dna.alt.fa"
> ref_path <-"splicewiz/ref_hg38"
> ref_path <-"ref_hg38"
> buildRef(
+   reference_path = ref_path,
+   fasta = genome,
+   gtf = gtf
+ )
Dec 19 11:04:52 AM Reference generated without non-polyA reference
Dec 19 11:04:52 AM Reference generated without Mappability reference
Dec 19 11:04:52 AM Reference generated without Blacklist exclusion
Dec 19 11:04:52 AM **Converting FASTA to local TwoBitFile...Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'X' in selecting a method for function 'sapply': memory allocation error in C_extract_character_from_raw_by_ranges()**

Could you please suggest a solution? I appreciate your time and help.

Kind regards
Reza

**Comment by alexchwong** [comment]
The error message suggests that the R session has run out of memory.

The human genome is 3.1 Gb, so ~ 4 Gb free RAM is required to prepare the genome assembly.

In general, we suggest at least 8 Gb free RAM to run the SpliceWiz pipeline. For functions that allow multiple threads, you will need more memory.

**Comment by rezarahman12** [comment]
Thanks, Alex for your quick response.
My laptop is 32GB (27GB usable) RAM. Could you please suggest me a way to avoid the above error?
Thanks a lot.
Best regards
Reza

**Comment by alexchwong** [comment]
I downloaded your genome file from ftp://ftp.ensembl.org/pub/release-108/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.alt.fa.gz and I assume this is the same file that you have.

I am able to reproduce high memory usage (> 32 Gb RAM usage) by doing the following:

fasta_file <- "Homo_sapiens.GRCh38.dna.alt.fa.gz"
genome <- Biostrings::readDNAStringSet(fasta_file)

So this appears to be an issue with the Biostrings package (pertaining to certain fasta files).

In contrast, using the primary assembly (https://ftp.ensembl.org/pub/release-108/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz), the following only consumes 4 Gb total:

fasta_file <- "Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz"
genome <- Biostrings::readDNAStringSet(fasta_file)

As I suggested (in #27), we recommend using the primary assembly. The "alt.fa" file only contains non-chromosomal elements and is NOT appropriate. Please use the primary assembly (or "toplevel", if the primary assembly is not available), thanks!

**Comment by rezarahman12** [comment]
Thanks a lot Alex. It worked well with the primary assembly file. I appreciate your time and help.
