### ISSUE TITLE
Collating Experiment error

### ISSUE THREAD

**Issue by jh4yd** [alexchwong/SpliceWiz#33]
Hi Alex,
I recently found your package, wanted to give it a try. I encountered an error when collating an experiment, as shown as the following. Any thought and solutions? I really appreciate it. 
Jing

**code**
#Collate the experiment
> nxtse_path <- file.path(working_dir, "NxtSE_output")
> collateData(
>     Experiment = expr,
>     reference_path = ref_path,
>     output_path = nxtse_path
> )

**output**
Jan 17 00:21:18 Using MulticoreParam 1 threads
Jan 17 00:21:19 Validating Experiment; checking COV files...
Jan 17 00:21:19 Compiling Sample Stats
Jan 17 00:21:19 Compiling Junction List...merging...done
Jan 17 00:21:36 Compiling Junction Stats...merging...done
Jan 17 00:21:47 Compiling Intron Retention List...done
Jan 17 00:22:05 Tidying up splice junctions and intron retentions...
...annotating splice junctions
Error in stop_if_wrong_length("'seqnames'", ans_len) : 
  'seqnames' must have the length of the object to construct (1) or length 1

**Comment by alexchwong** [comment]
Hi there,

One possibility for this error could be that none of the novel junctions found in your samples match that of the reference. I have updated the main branch to fix this issue. Please re-install SpliceWiz using the main branch:
`devtools::install_github("alexchwong/SpliceWiz")`

Let me know if the error persists

**Comment by alexchwong** [comment]
* correction - the seqnames of the novel junctions aren't matching the seqnames (chromosome names) of the reference

**Comment by jh4yd** [comment]
Hi Alex, Thank you for your prompt response. And you are right, these bam files were generated by using UCSC's reference instead of Ensembl. The problem was solved by using correct reference file. Thank you so much!
