### ISSUE TITLE
about deltaPSI 

### ISSUE THREAD

**Issue by rezarahman12** [alexchwong/SpliceWiz#34]
Hi Alex,
This is not an issue but rather a question about one of the parameters of SpliceWiz. 
To get significant differential events, I saw in the quick start tutorial of SpliceWiz,  we can obtain a list of differential events with delta PSI > 5%, res_limma.filtered <- subset(res_limma, abs(deltaPSI) > 0.05). My question is that if I use deltaPSI > 0.2 would that mean the differential events between condition B versus A are more confident than deltaPSI >0.05? 

my code is below-
res_edgeR.filtered <- subset(res_edgeR, abs(deltaPSI) > 0.2 & 
                                PValue< 0.05)

I would highly appreciate your time and comments.
Best regards
Reza

**Comment by alexchwong** [comment]
As this is a question about using the package and not an issue / bug report, I'd appreciate if you ask questions at the (Bioconductor support forums)[https://support.bioconductor.org/].

**Comment by rezarahman12** [comment]
Thanks, Alex. I did it.
