### ISSUE TITLE
buildRef with local gtf has minor bugs

### ISSUE THREAD

**Issue by jiaco** [alexchwong/SpliceWiz#39]
Hello
Thanks for this R package. I had to modify the R/BuildRef.R as shown in the diff below in order to get this to work.
```
1244c1244
<                 which(colnames(mcols(gtf_gr))) == "gene_type"
---
>                 which(colnames(mcols(gtf_gr)) == "gene_type" )
1253c1253
<                 which(colnames(mcols(gtf_gr))) == "transcript_type"
---
>                 which(colnames(mcols(gtf_gr)) == "transcript_type" )
```

**Comment by iamnicogomez** [comment]
i'm also having an issue with using a local (gencode) gtf. Exits with:
`Mar 22 16:42:58 Reference generated without non-polyA reference
Mar 22 16:42:58 Reference generated without Mappability reference
Mar 22 16:42:58 Reference generated without Blacklist exclusion
Mar 22 16:42:59 Connecting to genome TwoBitFile...done
Mar 22 16:42:59 Reading source GTF file...done
Error in which(colnames(mcols(gtf_gr))) : 
  argument to 'which' is not logical`

But using the chrZ_*() pair works fine. Which lines specifically did you modify jiaco?

Nico

**Comment by jiaco** [comment]
Look in the above diff and make those changes to the R/BuildRef.R source code (downloaded from GitHub or Bioconductor) line numbers are in the diff 1244 and 1253

and then re-install the package from your modified source with 
```
install.packages( "/path/to/modified/SpliceWiz", repos = NULL, type="source")
```

**Comment by iamnicogomez** [comment]
Ah, thank you. And it appears this has already been modified going from the bioconductor to latest github release. before i modify the source code im going to first use the latest github version and let you know if this bug has been solved.

**Comment by jiaco** [comment]
If this was already fixed, then I apologize in advance.
I had modified the Bioconductor source and then tried a re-install from GitHub but was not able to get it to work before installing with those modifications.

**Comment by iamnicogomez** [comment]
The github version appears to have the same issue although lines 1244 and 1253 are different. I'm going to reinstall the bioconductor version and make the change that worked for you, jiaco.

**Comment by alexchwong** [comment]
Thanks guys for the bug report. I have fixed the issue in the latest version of SpliceWiz (in branch "1.1.7-devel") and made a push to release version (1.0.2 -> 1.0.3) which will propagate in the next few days. Once 1.1.7 is ready, it will become the main branch (which is currently at devel 1.1.6)

To install:
release: devtools::install_github("alexchwong/SpliceWiz", "Bioc_3_16")
devel: devtools::install_github("alexchwong/SpliceWiz", "1.1.7-devel")

**Comment by alexchwong** [comment]
Please note that from versions 1.1.6+, reference and collated experiment (NxtSE) files are not compatible with previous versions
