### ISSUE TITLE
Build Reference issue: Column 'ccds_id' not found

### ISSUE THREAD

**Issue by sdimitrije** [alexchwong/SpliceWiz#44]
Hi,

It seems that it is impossible to construct a reference using either custom fasta+gtf or ensembl genome and transcriptome from within the GUI. 

Warning: Error in read_fst: Column 'ccds_id' not found

This occurs after PM Splice Annotations finished

This column is not supposed to exist in ensembl annotations anyway as far as i'm aware? Please advise on working around this issue.

Best,
Dimitrije

**Comment by alexchwong** [comment]
hi Dimitrije

Could you advise what species and ensembl release with which you were attempting to build the reference?

ccds_id column is certainly used for Ensembl human and mouse but I suspect it is not used with some species

**Comment by sdimitrije** [comment]
Hi Alex,

Thanks for the quick response. Sorry for the missing info, I was trying to build D. melanogaster reference.
Previously I did not have this problem a couple of months ago, although I'm unsure of the exact version used at the moment as I currently don't have access to the data.

**Comment by reck999** [comment]
I am also having this issue with building a reference for C. elegans, ensemble 70.

**Comment by alexchwong** [comment]
Apologies @sdimitrije for the delayed update. This issue should now be fixed in devel version 1.3.3 which can be installed via devtools::install_github(). It should also be available on Bioconductor devel in coming days if it passes all checks. Once this occurs, I will update Bioconductor release for the same changes.

**Comment by reck999** [comment]
Thank you!!

**Comment by alexchwong** [comment]
Fix is now being pushed to Bioconductor 3.17 (SpliceWiz version 1.2.3). It should be available from there in the next day or so.
