### ISSUE TITLE
buildRef()

### ISSUE THREAD

**Issue by chrismahony** [alexchwong/SpliceWiz#53]
Hi 

I get the follwing error when trying to build a reference, any help is greatly appreciated! Thanks

FTP <- "ftp://ftp.ensembl.org/pub/release-94/"

buildRef(
    reference_path = "/home/BulkSeq/splice_ref",
    fasta = paste0(FTP, "fasta/homo_sapiens/dna/",
        "Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz"), 
    gtf = paste0(FTP, "gtf/homo_sapiens/",
        "Homo_sapiens.GRCh38.94.chr.gtf.gz"),
    genome_type = "hg38"
)
```

Nov 02 16:06:43 Reference generated without Blacklist exclusion
Nov 02 16:06:46 Connecting to genome TwoBitFile...done
Nov 02 16:06:46 Reading source GTF file...done
Error: Nov 02 16:06:59 In .validate_gtf_chromosomes(), Chromosomes in genome and gene annotation does not match likely incompatible FASTA and GTF file

**Comment by alexchwong** [comment]
What version of SpliceWiz are you using? I cannot reproduce the error on my end

**Comment by chrismahony** [comment]
v1.2.3
Thanks

**Comment by alexchwong** [comment]
I can't reproduce this using version 1.2.3

I suggest you try to download the files from Ensembl's FTP repository and try to run buildRef using local files.

**Comment by chrismahony** [comment]
Thanks this work for buildref()

I have also run processBAM() and collateData() and it seems to complete.

But When I run:

se.filtered <- se[applyFilters(se),]
Running Depth filter
Running Participation filter
Running Participation filter
Running Consistency filter
Running Terminus filter
Running ExclusiveMXE filter
Running StrictAltSS filter
> 
> 
> require("edgeR")
> res_edgeR <- ASE_edgeR(
+     se = se.filtered,
+     test_factor = "condition",
+     test_nom = "EV",
+     test_denom = "R1C"
+ )
Error: Nov 08 21:57:55 No events for ASE analysis after filtering

I have also tried applying differnt filters:
se.filtered <- se[applyFilters(se,filters[[3]]),]

But it returns a similar/same error message.

I seem to have calculates splicing events in me se object:
rownames(se)[1:10]
 [1] "MIR1302-2HG/ENST00000469289_Intron1/anti-near" "OR4G11P/ENST00000642116_Intron1/clean"        
 [3] "OR4G11P/ENST00000642116_Intron2/clean"         "OR4F5/ENST00000641515_Intron2/clean"          
 [5] "AL627309.3/ENST00000495576_Intron1/known-exon" "AL627309.1/ENST00000466430_Intron2/clean"     
 [7] "AL627309.1/ENST00000471248_Intron2/clean"      "AL627309.1/ENST00000477740_Intron2/clean"     
 [9] "AL627309.1/ENST00000466430_Intron1/clean"      "AL627309.1/ENST00000471248_Intron1/clean" 


If you have any thoughts I would really appreciate it.

**Comment by alexchwong** [comment]
Are there any events if you run the analysis without using filters?

It may be possible the sequencing data in your project is not sufficiently deep to register enough reads to pass the depth filters?

**Comment by chrismahony** [comment]
WHen I try with the unfiltered:

require("edgeR")
res_edgeR <- ASE_edgeR(
    se = se,
    test_factor = "condition",
    test_nom = "EV",
    test_denom = "R1C"
)

I also get:

Warning: At least one library size is zeroError in .compressOffsets(y, lib.size = lib.size, offset = offset) : 
  offsets must be finite values

**Comment by alexchwong** [comment]
Hi Chris,

Apologies for the late reply but was hoping you had figured out the problem in the process.

`Warning: At least one library size is zeroError in .compressOffsets(y, lib.size = lib.size, offset = offset)`

The error message suggests at least one sample has zero counts. This can result either from alignment to the wrong reference, or other errors with the alignment step. I suggest troubleshooting the alignment files. To assist, `sampleQC(se)` will display, among other things, the sequencing `depth` and annotated splice junction counts.

**Comment by chrismahony** [comment]
This is what I get, any thoughts are much appreciated, thanks:

> head(sampleQC(se))
                         path paired strand     depth mean_frag_size directionality_strength Intergenic_Fraction rRNA_Fraction NonPolyA_Fraction
EV1   ../pb_output/EV1.txt.gz  FALSE      0  99070046       149.5406                       0                   0             0                 0
EV2   ../pb_output/EV2.txt.gz  FALSE      0 101149219       149.4900                       0                   0             0                 0
EV3   ../pb_output/EV3.txt.gz  FALSE      0  73541855       149.5072                       0                   0             0                 0
R1A1 ../pb_output/R1A1.txt.gz  FALSE      0  71733797       149.4712                       0                   0             0                 0
R1A2 ../pb_output/R1A2.txt.gz  FALSE      0 103229220       149.5798                       0                   0             0                 0
R1A3 ../pb_output/R1A3.txt.gz  FALSE      0  82042618       149.5259                       0                   0             0                 0
     Mitochondrial_Fraction Unanno_Jn_Fraction NMD_Jn_Fraction Fraction_Splice_Reads Fraction_Span_Reads IRBurden_clean IRBurden_exitrons
EV1                       0                NaN             NaN                     0                   0              0                 0
EV2                       0                NaN             NaN                     0                   0              0                 0
EV3                       0                NaN             NaN                     0                   0              0                 0
R1A1                      0                NaN             NaN                     0                   0              0                 0
R1A2                      0                NaN             NaN                     0                   0              0                 0
R1A3                      0                NaN             NaN                     0                   0              0                 0
     IRBurden_clean_unstranded IRBurden_exitrons_unstranded IRBurden_antisense
EV1                        NaN                          NaN                NaN
EV2                        NaN                          NaN                NaN
EV3                        NaN                          NaN                NaN
R1A1                       NaN                          NaN                NaN
R1A2                       NaN                          NaN                NaN
R1A3                       NaN                          NaN                NaN

**Comment by alexchwong** [comment]
Have you checked whether your BAM files are aligned to the same genome as that of your SpliceWiz reference?

I wonder whether this result is due to BAM files having Gencode chromosomes (chr1, chr2, ...) which will not match Ensembl chromosomes (1, 2, ...)

**Comment by chrismahony** [comment]
yes they are both using GRCh38 and both are 1,2,3 and not chr1, chr2 etc.

When I look at the .txt.gz file for a sample in the pb_output folder (generated after processBAM()), does this look normal?

BAM_report      Value
Total reads processed   99070046
Total nucleotides       14814998604
Total singles processed 99070046
Total pairs processed   0
Short pairs     0
Intersect pairs 0
Long pairs      0
Skipped reads   0
Chimeric reads  0

**Comment by alexchwong** [comment]
Looks like your dataset is 150-nt single-end reads at ~100 mil reads / sample.

I'm unsure why SpliceWiz is detecting zero exon-exon spliced reads and exon-intron spanning reads (`Fraction_Splice_Reads` and `Fraction_Span_Reads`, respectively). To troubleshoot, perhaps you can open a BAM file on IGV and see if you can see any splicing across exons. To keep things simple, look at a housekeeper gene e.g. ACTB or B2M.

**Comment by chrismahony** [comment]
I have already tried this and I dont see splicing

Could this be an alignment problem? it was done using bowtie2, would you recommend another method?
