### ISSUE TITLE
BuildRef Ensure there are valid entries with type == `CDS`"

### ISSUE THREAD

**Issue by droplet-lab** [alexchwong/SpliceWiz#56]
Thanks for putting together spliceWiz,

I was trying to build the reference using standard Ensembl annotation and fasta but ran in the error 
Ensure there are valid entries with type == `CDS`"

Not sure what I am doing wrong bu could you perhaps point towards what the problem could be ? I have pasted the outputs hereunder:

Thanks a lot!!

> buildRef(
+   reference_path = ref_path,
+   fasta = "/path/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa" ,
+   gtf = "/path/Homo_sapiens.GRCh38.107.gtf",
+   ontologySpecies = "Homo sapiens"
+ )
Jan 03 10:04:44 Reference generated without non-polyA reference
Jan 03 10:04:44 Reference generated without Mappability reference
Jan 03 10:04:44 Reference generated without Blacklist exclusion
Jan 03 10:04:44 Connecting to genome TwoBitFile...done
Jan 03 10:04:44 Reading source GTF file...done
Jan 03 10:04:51 Processing gtf file...
...genes
...transcripts
...CDS
Error in paste("No protein information detected in reference!", "Ensure there are valid entries with type == `CDS`",  : 
  argument is missing, with no default

**Comment by droplet-lab** [comment]
Hi Alex, thanks, I get the following

> gtf <- rtracklayer::import("/path/Homo_sapiens.GRCh38.107.gtf", "gtf")
> table(gtf$type)

           gene      transcript            exon             CDS     start_codon      stop_codon  five_prime_utr 
          61860          251121         1624585          871196           96934           90724          171504 
three_prime_utr  Selenocysteine 
         203201             119

**Comment by alexchwong** [comment]
Hmm not sure why that error is triggered given there are legit CDS / start codon entries in your gtf. Nevertheless, the latest version of SpliceWiz on bioconductor (1.4.1 release or 1.5.2 devel) has expanded compatibility with custom gtfs with incomplete metadata, I suggest you give this a try.
