### ISSUE TITLE
Missing exons in SpliceWiz.ref.gz

### ISSUE THREAD

**Issue by akikuno** [alexchwong/SpliceWiz#58]
Thank you for developing SpliceWiz.

I used SpliceWiz for a differential analysis between a sample with exon 2 of the Strap gene deleted as a positive control and wild-type. However, the positive control (exon 2 of the Strap gene) was not detected. I suspect this may be due to the absence of Strap's exon in the SpliceWiz.ref.gz generated by the `buildRef` function. Is this the case? If so, why is Strap's exon not included in SpliceWiz.ref.gz, and how can I include it? I would appreciate your guidance.

![image](https://github.com/alexchwong/SpliceWiz/assets/15861316/f2498334-a002-4833-b54a-3e3d4ebbe231)

Below are the steps to reproduce.

## Setup environment by conda

```bash
conda create -y -n splicewiz python=3.10
conda install -y -n splicewiz -c conda-forge -c bioconda -c defaults bioconductor-splicewiz
conda activate splicewiz

conda list | grep splicewiz
# bioconductor-splicewiz    1.4.0             r43hf17093f_0    bioconda
```

## Download reference genome and annotation

```bash
mkdir -p data/genome
wget -O - https://ftp.ensembl.org/pub/current_fasta/mus_musculus/dna/Mus_musculus.GRCm39.dna.primary_assembly.fa.gz |
gzip -dc > data/genome/mm39.fa

wget -O - https://ftp.ensembl.org/pub/current_gtf/mus_musculus/Mus_musculus.GRCm39.111.gtf.gz |
gzip -dc > data/genome/mm39.gtf
```

## Build reference

```R
library(SpliceWiz)
ref_path <- "data/genome/splicewiz"
buildRef(
    reference_path = ref_path,
    fasta = "data/genome/mm39.fa",
    gtf = "data/genome/mm39.gtf",
    ontologySpecies = "Mus musculus"
)
```

## Grep Strap

```bash
zcat data/genome/splicewiz/SpliceWiz.ref.gz | grep Strap
```

**Comment by alexchwong** [comment]
Hi @akikuno 

`SpliceWiz.ref.gz` is a data reference to inform the program which introns should be evaluated for IR. It is not used for other forms of alternative splicing.

It is best if you peruse the reference for the alternative splicing reference using `viewASE()`. For your specific task, I suspect you are looking for skipped exon event of Strap exon 2.

**Comment by akikuno** [comment]
@alexchwong 

Thank you so much for your guidance! I will look into it.
