### ISSUE TITLE
NxtSE Loading Failed

### ISSUE THREAD

**Issue by DarioS** [alexchwong/SpliceWiz#62]
Any idea why loading failed? Experiment has only one sample for testing purposes.

> Apr 11 12:07:08 PM Generating NxtSE assays
> Apr 11 12:07:11 PM Building Final NxtSE Object
> Apr 11 12:07:11 PM ...consolidating assays to H5 file
> Apr 11 12:07:14 PM ...packaging reference
> Apr 11 12:07:15 PM ...synthesising NxtSE
> Apr 11 12:07:15 PM ...determining how overlapping introns should be removed
> Error: Apr 11 12:07:17 PM Test loading of NxtSE object failed.

**Comment by GiulyN** [comment]
I am getting the same error when I run collateData

mag 30 17:04:00 Generating NxtSE assays
mag 30 17:04:24 Building Final NxtSE Object
mag 30 17:04:24 ...consolidating assays to H5 file
mag 30 17:04:35 ...packaging reference
mag 30 17:05:03 ...synthesising NxtSE
mag 30 17:05:18 ...determining how overlapping introns should be removed
Errore: mag 30 17:05:33 Test loading of NxtSE object failed.

**Comment by alexchwong** [comment]
I don't think SpliceWiz supports experiments with only 1 sample, because differential analyses cannot be performed

I suggest you try at least 4 samples so there can be a 2v2 comparison. Also please advise the SpliceWiz version being used.
