### ISSUE TITLE
STAR_BuildRef Error

### ISSUE THREAD

**Issue by GimenaA** [alexchwong/SpliceWiz#63]
Hello,
I'm getting an error when trying to run the STAR_BuildRef() function. It says: **Error in STAR_BuildRef(reference_path = ref_path, STAR_ref_path = "/home/gimena/SpliceWiz/Reference/STAR_genome_BDGP6_46",  : could not find function "STAR_BuildRef."** However, when I run the STAR_buildGenome() function it works fine. 

STAR version: 2.7.10a
SpliceWiz version: 1.5.3
R version 4.2.1 (2022-06-23)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 22.04.4 LTS

**Comment by alexchwong** [comment]
Hi there,

You may want to update to the latest version of SpliceWiz. 1.5.3 is quite an old version

**Comment by GimenaA** [comment]
Is SpliceWiz_1.7.2 the latest version? I updated SliceWiz. But I still get the same error with the STAR BuildRef function.
