### ISSUE TITLE
collateData error

### ISSUE THREAD

**Issue by alicinwndlnd** [alexchwong/SpliceWiz#64]
Hi,

I'm trying to run collateData but I've been getting this error 
**Error: Object 'exon_group_up' not found amongst [seqnames, start, end, Name, Null, strand]**
during "...grouping introns".
I'm not sure what's the issue is but I think it might related to  ".overlaps_exon_island" not running properly. And I couldn't find this function anywhere.

**Comment by alexchwong** [comment]
Hi there,

Please provide version of SpliceWiz being used. Latter versions have work-arounds to deal with GTF files without valid exon_number annotations.
