### ISSUE TITLE
Singularity container definition file

### ISSUE THREAD

**Issue by clydeugene** [alexchwong/SpliceWiz#65]
Hi Alex. I've been struggling to install SpliceWiz on WSL2 and Ubuntu using conda or directly in R then I stumbled upon the singularity container on Biocontainers and it's been working so far.

From the steps in the cookbook, I may need to run STAR, which is not included in the container. Might you be able to share the container definition file so I can make a custom copy with Star included?

**Comment by alexchwong** [comment]
Hi there,

I'm not sure STAR is compatible with windows. Have you tried HISAT2? If not, you could consider using Rsubread; or use a public Galaxy server to create BAM alignment files from the raw FASTQs.

**Comment by clydeugene** [comment]
I'm sorry for not responding earlier. I ended up skipping this step of the analysis but I will try your suggestions when I have a little more free time.
