### ISSUE TITLE
Error on reference building

### ISSUE THREAD

**Issue by t3h4nt1chr15t** [alexchwong/SpliceWiz#69]
No matter if I use manually downloaded genome and genome reference files or Iuse the GUI to build it through SpliceWiz, I always get the same error:

"Warning: Error in : Sep 11 4:09:06 PM In .validate_gtf_chromosomes(), Chromosomes in genome and gene annotation does not match likely incompatible FASTA and GTF file"

There doesn't seem to be a way around this error, even using different distributions and releases of ensemble genome files doesn't work.

**Comment by t3h4nt1chr15t** [comment]
As an update, I've tried releases 113, 112, 102, and 108. I've done this via supplying a manual address to files I've already downloaded and I've also done this by selecting these releases in the GUI itself. No matter what I chose, I always get the "Chromosomes in genome and gene annotation does not match" error. I'm seeing this has been reported by others as well but I think I'm the only one reporting that it's happening in the GUI as well, not just with manually provided files. 

Can you confirm that this package has been validated to work with any ENSEMBLE release on Windows platforms? I noticed all the code you've posted in guides is from linux environments. I just want to have a release of ENSEMBLE that I can confirm works on my machines that you've also confirmed, so I can eliminate any possibilities of the package being installed improperly or lacking dependencies.

**Comment by t3h4nt1chr15t** [comment]
I have confirmed that the chrZ demo files provided in the package do build completely without this error, which is why I wanted to get confirmation that you've validated this in a full genome file on Windows. Additionally, I'm doing this in mouse genomes, if that matters at all. I did notice the example files you always use in the guides are with humans...

**Comment by t3h4nt1chr15t** [comment]
Okay, so I did some troubleshooting. I get the exact same error when I change the reference building code you provided here:

ref_path <- file.path("S:/Computation/R/SpliceWiz")
buildRef(
  reference_path = ref_path,
  fasta = chrZ_genome(),
  gtf = chrZ_gtf(),
  ontologySpecies = "Homo sapiens"
)

to instead this:

ref_path <- file.path("S:/Computation/R/SpliceWiz")
buildRef(
  reference_path = ref_path,
  fasta = chrZ_genome(),
  gtf = chrZ_gtf(),
  ontologySpecies = "Mus musculus"
)

So changing only the species reproduces the same error. But, entering the wrong species wouldn't make the chromosomes in the genome and annotation file not match, since they are indeed compatible. So it is likely that the error stating these files don't match doesn't have anything to do with the files not actually being compatible, but instead there seem to be multiple issues that would cause the package to spit this error out, making it more of a general error, non-specific to file compatibility. 

Unfortunately this makes it impossible for me to determine what is actually wrong. I'm entirely dependent on you being able to reproduce this error on your end and chasing down the cause. So if you could confirm you can reproduce this error in the GUI or manually from a windows computer on say, the 102 release of ENSEMBLE, that would be very helpful, thank you. Or if you can confirm you've done this on windows without the error, providing me with those details would let me validate those details on my end at least.

**Comment by t3h4nt1chr15t** [comment]
I've also finished trying this in multiple fasta and gtf formats:

The fasta files from ENSEMBLE can come in .fa formats as well as .fasta formats
The gtf formats can come in .gtf or .gff3

I've now done every possible combination of those formats in the manual code of reference building in the spliceWiz package, specifically with the 102 ENSEMBLE release. All of them result in the same "Chromosomes in genome and gene annotation does not match" error.

**Comment by alexchwong** [comment]
> Chromosomes in genome and gene annotation does not match

This occurs when the chromosome names in the FASTA file and GTF file do not match. This most commonly occurs when the FASTA file contains both the chromosome name and a description line, e.g. "chr1 [more info about chromosome]" instead of simply "chr1". The GTF file will only have "chr1" - hence the mismatch in chromosomes.


I have updated SpliceWiz to v 1.7.4 (currently on Bioc Devel) which will auto-fix the fasta file; and working on a fix for 1.6.4 (for current release Bioc 3.19) right now.

If you wish to use an older version of SpliceWiz, you may wish to fix the FASTA file yourself.

**Comment by t3h4nt1chr15t** [comment]
I've updated SpliceWiz to v 1.7.4

Unfortunately that hasn't changed anything. I still get the same error with the ENSEMBLE 102 release for Mus Musculus. This is while using the GUI in your package too, so they are with the files that you've determined to be matching.

I'll continue doing some troubleshooting, but so far nothing has been fixed.

**Comment by t3h4nt1chr15t** [comment]
I really think this might not have anything to do with the files being incompatible or in different formats. The fact that I was able to get this error message with your own demo files shows that the error message can be generated for reasons besides the files not matching.

Can you verify that this package has been validated with a full genome and gtf file from ENSEMBLE on a Windows platform? I'm very suspicious of this factor as you use OpenMP for the basis of your multithreading which is notorious for having issues on Windows platforms as it hasn't been update for 3 years now.

**Comment by t3h4nt1chr15t** [comment]
I've now done this in multiple ENSEMBLE releases, both manually and through the GUI in SpliceWiz. I've also done this after editing the fasta file to remove the description component of the header, like you said I could alternatively do. All under the most recent SpliceWiz version, 1.7.4.

None of this is working, I still get the exact same "genome and gene annotation does not match" error, but it's not an issue with the description because the description is now confirmed to be gone in the fasta.

Can you please verify this works with **any** full ENSEMBLE release files and tell me what release you used. If we can at least confirm it works with any full release files, I can do the same to eliminate a bunch of other potential contributing factors, like operating system.

**Comment by t3h4nt1chr15t** [comment]
I've also tried to find other ways that this error could be given. I already found that changing the species produces the "genome and gene annotation does not match" error. So that is a way the error is given that has nothing to do with the genome and gene annotation files not matching.

I've also now just given it the file name of a file that does not exist. Something that it should probably give an error for saying something along the lines of "file not found." But it still gives the exact same error. This error seems to be given for just about any reason the package fails to build the reference file. I think you need to start looking for other reasons this could be occurring besides the genome files not matching, because they do match, and it's not the description component that's causing the error. 

I really do think this should start with you validating this on Windows, or at least providing the metadata and environment info you've already validated it under in Linux, along with what ENSEMBLE release files you used. With any error giving this same error message, it will be impossible for me to verify on my end the actual reason this error is occurring. So the only way to troubleshoot it, besides you taking a crack at any random bug fix and hoping it addresses the issue I have, is to start from the same foundation. If I can know what the circumstances were for the validation you've done with full ENSEMBLE files, we can do that.

**Comment by alexchwong** [comment]
I can confirm several things:

1) Ensembl mouse and human references can be built using SpliceWiz > 1.7.4 on Windows 10 on my end.
2) The package is tested on multiple platforms on a regular basis - see https://bioconductor.org/checkResults/release/bioc-LATEST/SpliceWiz/ and https://bioconductor.org/checkResults/devel/bioc-LATEST/SpliceWiz/

If you have an issue regarding how the package is being tested (see files in the "tests/testthat" subfolder), please submit a separate issue.

If you have recurrent issues with the "genome and gene annotation does not match" error, I suggest you first confirm it is not a problem with the fasta and gtf files on your end, by running the following

```
library(GenomeInfoDb)
library(GenomicRanges)

genome <- rtracklayer::import("genome.fa", "fasta")
gtf <- rtracklayer::import("transcripts.gtf", "gtf")

chrGenome <- names(seqinfo(genome))
chrGTF <- as.character(seqnames(gtf))

# To remove spaces
library(data.table)
chrGenome <- unname(sapply(chrGenome, function(x) tstrsplit(x, split = " ", fixed = TRUE)[[1]]))

# To check there are common chromosome names in fasta and gtf file
any(chrGTF %in% chrGenome)
```

**Comment by t3h4nt1chr15t** [comment]
1) I'm doing this with not just manually provided fasta and gtf files, but also the files you automate for through the GUI, so I would not assume it is an issue with these files on my end as half of the validation I've done is with your automated processes, not my manually provided files.

2) Can you please provide me with the release and species for the ENSEMBLE files you used? Providing a link would be even better. The whole reason I've been asking this is so that I can eliminate a lot of potential causes for these errors. The best way to do that is to have the exact files you used to validate the package. That should be relatively straightforward if you've validated this on windows 10. So please just tell me which ENSEMBLE files you used or provide the link to their download source if you can. 

In the meantime, I'll give your block of code a shot, but I don't think it will reveal anything noteworthy as, as I've said before, this isn't just a problem with my manually provided files, but also with the automated ones through your GUI. I also got these errors with your own demo files.

**Comment by t3h4nt1chr15t** [comment]
I used your block of code on three different file combinations. One with manually downloaded files for ENSEMBLE 102, one with the same files that I removed the description headers from (at your recommendation), and one that was downloaded by your own GUI from the package. All three resulted in a FALSE, for the check of common chromosome names in fasta and gtf file.

**Comment by t3h4nt1chr15t** [comment]
If this is an issue with a specific species, I wouldn't know unless you told me what species ENSEMBLE you validated with.

If this is an issue with a specific release of ENSEMBLE, I wouldn't know unless you told me what release of ENSEMBLE you validated with.

Please tell me those two things. 

I understand this is frustrating. I understand I'm being very direct, but I'm not trying to tell you how to do your job, I'm just trying to troubleshoot this. I was very excited when I saw someone made a splicing analysis package for R finally, especially when I've had so many problems in Python before with other packages. I would very much like to include your package in my research publication, but I can't do that if I can't even get the reference file to build. I would very much appreciate your help. I don't think I can get this working without you.

**Comment by t3h4nt1chr15t** [comment]
Just to update this thread. I got around this issue by using SpliceWiz on a Macbook Pro. But apart from not using more threads in the Windows OS, which SpliceWiz documentation does rightly say not to do in Windows; the code, R environment, etc, are all the same on the MacBook. So seemingly, the only thing that's changed is that I'm running this in a Mac environment rather than a Windows environment. 

All of the issues went away that I was experiencing before and now the reference builds with no errors spat out at all. I think this supports my earlier assertions that maybe the Windows compatibility you reported isn't as compatible as you believe it to be. 

I used the same GUI and the same manual files, meaning the genome reference files weren't corrupted like you thought they might be and there were no other issues with the headers or chromosomes not being labeled either as again, it worked just fine on a MacBook pro with nothing else changed about what I did.

That all being said, while I think the reference building problem was resolved by not running it on Windows, I am now running into new issues, which I reported in another bug post, in the BAM processing step.

**Comment by alexchwong** [comment]
I maintain that there are no errors encountered with human and mouse genomes from Ensembl.

The fact that it works on your Mac and not on your Windows is probably an installation issue.

I can confirm that SpliceWiz was developed on the Windows platform. Moreover, as already mentioned, the specific issues you raised are being tested on unit testing and confirms to pass on Win / Mac / Linux.

I suggest you look at the `check of common chromosome names` code being run earlier as to why the FASTA and GTF chromosome names are not matching.

Closing this thread as it is no longer a bug report with a reproducible example.
