### ISSUE TITLE
Error Building Human Reference

### ISSUE THREAD

**Issue by Omics66427** [alexchwong/SpliceWiz#72]
Hi,

I tried building my own human reference as well as the reference in the SpliceWiz example:
```
ref_path <- file.path(tempdir(), "Reference")
buildRef(
    reference_path = ref_path,
    fasta = chrZ_genome(),
    gtf = chrZ_gtf(),
    ontologySpecies = "Homo sapiens"
)
```
But I keep running into the same error **"Error in match.arg(type) : 'arg' must be NULL or a character vector"**

After additional testing, it appears that this error specifically occurs when I use the ontologySpecies = "Homo sapiens" and/or genome_type = "hg38" options.

If I omit those options and run:
```
getResources(
  reference_path = ref_path,
  fasta = chrZ_genome(),
  gtf = chrZ_gtf()
)

buildRef(
  ref_path
)
```
it runs successfully.

SpliceWiz_1.7.5
R version 4.4.1

**Comment by alexchwong** [comment]
Hi there,

It appears the OrgDB entries for Homo sapiens and Mus musculus have been recently removed in AnnotationHub for Bioc 3.19, then re-entered into the database for Bioc devel (3.20).

The following code returns `TRUE` in Bioc 3.20 but `FALSE` in Bioc 3.19:
```
library(AnnotationHub)
ah <- AnnotationHub()
ah_orgList <- subset(ah, ah$rdataclass == "OrgDb")
supportedSpecies <- unique(ah_orgList$species)
any(supportedSpecies == "Homo sapiens")
```

So this is an issue with Bioc 3.19 and AnnotationHub
For a work-around I suggest use Bioc devel
