### ISSUE TITLE
Error when processing BAMs

### ISSUE THREAD

**Issue by t3h4nt1chr15t** [alexchwong/SpliceWiz#74]
I resolved my earlier issue with the reference never building by getting an M1 Macbook Pro. But now that I've been able to build the reference, the BAMs themselves wont process.

When using the GUI, processing BAMs leads to a runtime error and it says there's a BiocParallel error as well: "1 remote errors, element index: 1." This error occurs whether I'm using multiple threads or one thread. And finally, there is also an error in the last line reported in R "SpliceQiz processBAM failed to produce ...experiments/sample.txt.gz".

I've also done this with the manual code instead and this leads to the same error.

Not sure where to go from here as I haven't seen this reported as a bug before with your package.

**Comment by alexchwong** [comment]
Please provide what manual code was used to run, and the error message please.

**Comment by t3h4nt1chr15t** [comment]
I resolved the issue. Forgot to put that here, sorry!
