### ISSUE TITLE
"sluggish" BAM processing error

### ISSUE THREAD

**Issue by t3h4nt1chr15t** [alexchwong/SpliceWiz#76]
There are a couple bams in my data set that routinely fail to be processed due to SpliceWiz saying the process seems 'sluggish.' They also happen to be our biggest bam files. Over 20GB in size. I've gone out of my way to try to verify they weren't corrupted and only have one thing left to confirm that this was not the case, so I wanted to reach out and probe a bit on this error message.

When this happens, is it due to the process taking too long, or is it actually getting caught up on any specific step? Our bams are very deep short-read. If the error is occurring due to it just taking to long, that would be due to the size of the file more than anything else so is this a setting we can disable to give it more time so that it can finish the processing? If not, what else might cause this error besides a corrupted bam file, as I'm fairly certain now that the bams are intact.

For context, our bams are coordinate-sorted using Rsubread, not STAR or any of the other more popular methods of bam sorting. I'm aware that the rest of the error message suggests sorting by read name to get around this, but the SpliceWiz package does state it is compatible with coordinate-sorted bams and read name sorting isn't currently an option for us as Rsubread does not allow for that kind of sorting and we don't have STAR set up on any of our lab devices.

**Comment by t3h4nt1chr15t** [comment]
To update, I've just tried a few more bam files that are above 20GB in size. Every one of them fails. Of the under 20GB bam files I've tried so far, none have failed. I'm currently running a list of 10 more bams that are under 20GB. If all of these bams under 20GB process successfully, then I think I've come to the issue, that there appears to be an arbitrary time limit set on the bam processing method in SpliceWiz. Or some other arbitrary setting established that prevents the processing of larger bams, at least in the context of coordinate-sorted bams.

**Comment by alexchwong** [comment]
This is a known limitation on how SpliceWiz processes paired RNA-seq alignment BAMs.

The solution (as documented) is to re-sort the BAMs using read name. This can be done using BAM utilities such as samtools and sambamba. E.g. see: http://www.htslib.org/doc/samtools-sort.html
