### ISSUE TITLE
Error in getCoverageData

### ISSUE THREAD

**Issue by mmilevskiy** [alexchwong/SpliceWiz#78]
Hi Team,

I have gone to re-open an analysis and several commands wont run anymore. This is the error I am getting with getCoverageData. 

Any thoughts are much appreciated!

Note: have removed the gene name to put code and traceback here. 

dataObj <- getCoverageData(se, Gene = "GENE", tracks = colnames(se))

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'drop': The extract_array() method for HDF5ArraySeed objects returned an array with incorrect
  dimensions. Please contact the authors/maintainers of the HDF5ArraySeed class
  (defined in the HDF5Array package) about this, and point them to the man page for the
  extract_array() generic function defined in the S4Arrays package
  ('?S4Arrays::extract_array').
22. h(simpleError(msg, call))
21. .handleSimpleError(function (cond)
.Internal(C_tryCatchHelper(addr, 1L, cond)), "The extract_array() method for HDF5ArraySeed objects returned an array with incorrect\n dimensions. Please contact the authors/maintainers of the HDF5ArraySeed class\n (defined in the HDF5Array package) about this, and point them to the man page for the\n extract_array() generic function defined in the S4Arrays package\n ('?S4Arrays::extract_array').",
base::quote(check_returned_array(ans, expected_dim, "extract_array",
class(x))))
20. stop(wmsg("The ", .Generic, "() method for ", x_class, " ", "objects returned an array with incorrect ",
"dimensions. ", .contact_author_msg1(.Generic, x_class)))
19. check_returned_array(ans, expected_dim, "extract_array", class(x))
18. extract_array(x2@seed, x2@index)
17. extract_array(x@seed, index)
16. extract_array(x@seed, index)
15. extract_array(x@seed, index)
14. extract_array(x@seed, index)
13. .nextMethod(x = x, index = index)
12. callNextMethod()
11. extract_array(x, index)
10. extract_array(x, index)
9. .from_Array_to_array(x, ...)
8. as.array.Array(x)
7. as.array(x)
6. drop(as.array(x))
5. .from_Array_to_matrix(x, ...)
4. as.matrix.Array(assay(args[["se"]], "Depth")[names(event_gr),
rownames(colData), drop = FALSE])
3. as.matrix(assay(args[["se"]], "Depth")[names(event_gr), rownames(colData),
drop = FALSE])
2. .gCD_retrieve_norms(args, colData)
1. getCoverageData(se, Gene = "GENE", tracks = colnames(se))

**Comment by mmilevskiy** [comment]
I am uncertain what the actual problem was, but I re-ran the entire analysis and it worked. Maybe a link to the data was missing after an update?

**Comment by alexchwong** [comment]
I am not sure as to why you encountered that particular error. It is good that you have resolved this by re-running the pipeline using the latest SpliceWiz.

Sometimes, SpliceWiz code need to be updated to maintain compatibility with changes in other Bioconductor packages on which it depends.
